import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import Nav from '@/components/navigations/nav';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/components/providers/theme-provider';
import Toaster from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={cn('px-6 md:px-12 max-w-7xl mx-auto', `${inter.className}`)}
        suppressHydrationWarning={true} //solves this problem Warning: Extra attributes from the server: cz-shortcut-listen
      >
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <Nav />
          <Toaster />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
